name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build frontend
        run: cd frontend && yarn install && yarn build

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u '+%Y-%m-%d %I:%M:%S %Z')"

      - name: Build binary
        run: |
          CGO_ENABLED=0 go build -v -ldflags " -X \"main.BuildTime=${{ steps.date.outputs.date }}\" -X \"main.BuildCommit=$GITHUB_SHA\"" -trimpath

      - name: Build & Publish to Registry
        uses: wuhan005/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          repository: registry.cn-hangzhou.aliyuncs.com/eggplant/asoul-video
          tag_format: "%YYYY%_%MM%_%DD%_%H%%m%%s%"
          auto_tag: true

      - name: Send notification to Discrod
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The asoul-video backend has been deployed. https://github.com/asoul-video/asoul-video/commit/{{ GITHUB_SHA }}'
